app/models/polling_station.py
import datetime
from app.extensions import db
from app.models.assembly_const import AssemblyConst
from sqlalchemy.ext.hybrid import hybrid_property


class PollingStation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    assembly_const_no = db.Column(db.Integer, db.ForeignKey('assembly_const.ac_no'), name='fk_assembly_const_no')
    part_no = db.Column(db.Integer, nullable=False)
    part_name = db.Column(db.String(150))
    ps_no = db.Column(db.Integer, unique=True, nullable=False)
    ps_code = db.Column(db.String(12), unique=True, index=True)
    ps_name = db.Column(db.String(150))
    ps_type = db.Column(db.String(150))
    ps_category = db.Column(db.String(150))
    location_type = db.Column(db.String(150))
    electors_male = db.Column(db.Integer, default=0)
    electors_female = db.Column(db.Integer, default=0)
    electors_other = db.Column(db.Integer, default=0)
    electors_total = db.Column(db.Integer, default=0)

    is_sangha = db.Column(db.Boolean, default=False)
    electors_male_sangha = db.Column(db.Integer, default=0)
    electors_female_sangha = db.Column(db.Integer, default=0)
    electors_other_sangha = db.Column(db.Integer, default=0)
    electors_total_sangha = db.Column(db.Integer, default=0)

    ps_election_officers = db.relationship('PsElectionOfficer', backref='polling_station', lazy=True)
    voters_turnouts = db.relationship('VotersTurnout', backref='polling_station', lazy=True)

    last_updated = db.Column(db.DateTime, server_default=db.func.now(), server_onupdate=db.func.now())
    created_at = db.Column(db.DateTime, server_default=db.func.now())

    # @hybrid_property
    # def ps_code(self):
    #     return f'{self.assembly_const_no if self.assembly_const_no > 9 else '0' + str(self.assembly_const_no)}/{self.part_no}'

    def on_create(self):
        self.created_at = datetime.datetime.now()
        
    def __repr__(self):
        return f'<PollingStation "{self.ps_name}">'

app/routes/toolkit/__init__.py
from flask import Blueprint

bp = Blueprint('toolkit', __name__)

from app.routes.toolkit import routes_ps
from app.routes.toolkit import routes_ac_el_officer
from app.routes.toolkit import routes_voters_turnout

app/routes/toolkit/routes.py
from flask import jsonify, render_template, request, url_for, redirect
from flask_login import current_user, login_required
from app.routes.toolkit import bp
from app.extensions import db
from app.models.user import User
from app.models.polling_station import PollingStation

import pandas as pd

@bp.route('/ps', methods=['GET', 'POST'])
@login_required
def ps():
    p_station = PollingStation.query.all()
    for role in current_user.roles:
        if role.name.startswith('ac_'):
            ac_no = role.name.split('ac_')[1]
            p_station = PollingStation.query.filter_by(ac_no=ac_no).all()
            break
    
    electors_mtotal = sum([p.electors_male for p in p_station])
    electors_ftotal = sum([p.electors_female for p in p_station])
    electors_ototal = sum([p.electors_other for p in p_station])
    electors_gtotal = sum([p.electors_total for p in p_station])

    el_grand_total = {
                        'mtotal': electors_mtotal, 
                        'ftotal': electors_ftotal, 
                        'ototal': electors_ototal,
                        'gtotal': electors_gtotal
                    }

    return render_template('toolkit/polling_station/index.html', p_station=p_station, el_grand_total=el_grand_total)

@bp.route('/ps/list', methods=['GET', 'POST'])
@login_required
def ps_list():
    p_station = PollingStation.query.all()

    # json rest response
    return jsonify([p.serialize for p in p_station])

@bp.route('/ps/update', methods=['POST'])
@login_required
def ps_update():
    data = request.get_json()
    p = PollingStation.query.get(data['id'])
    p.part_no           = data['part_no']
    p.part_name         = data['part_name']
    p.ps_no             = data['ps_no']
    p.ps_name           = data['ps_name']
    p.ps_type           = data['ps_type']
    p.ps_category       = data['ps_category']
    p.location_type     = data['location_type']
    p.electors_male     = data['electors_male']
    p.electors_female   = data['electors_female']
    p.electors_other    = data['electors_other']
    p.electors_total    = data['electors_total']

    db.session.commit()
    return jsonify({'msg': 'Data updated successfully'}), 200

@bp.route('/ps/delete', methods=['POST'])
@login_required
def ps_delete():
    data = request.get_json()
    p = PollingStation.query.get(data['id'])
    db.session.delete(p)
    db.session.commit()
    return jsonify({'msg': 'Data deleted successfully'}), 200

@bp.route('/ps/import', methods=['POST'])
@login_required
def ps_import():
    ac_no = None
    for role in current_user.roles:
        if role.name.startswith('ac_'):
            ac_no = role.name.split('ac_')[1]
            break
    if 'file' not in request.files:
        return jsonify({'msg': 'No file part'}), 400
    file = request.files['file']
    if file.filename == '':
        return jsonify({'msg': 'No selected file'}), 400
    if not file.filename.endswith('.xlsx'):
        return jsonify({'msg': 'Invalid file extension'}), 400
    
    df = pd.read_excel(file)

    for index, row in df.iterrows():
        p = PollingStation.query.filter_by(part_no=row['PART_NO'], ps_no=row['PS_NO']).first()
        if p is None:
            p = PollingStation()
            p.ac_no             = ac_no
            p.part_no           = row['PART_NO']
            p.part_name         = row['PART_NAME']
            p.ps_no             = row['PS_NO']
            p.ps_name           = row['PS_NAME_EN']
            p.ps_type           = row['PS_TYPE']
            p.ps_category       = row['PS_CATEGORY']
            p.location_type     = row['LOCN_TYPE']
            p.electors_male     = row['electors_male']
            p.electors_female   = row['electors_female']
            p.electors_other    = row['electors_other']
            p.electors_total    = row['electors_total']

            db.session.add(p)
    db.session.commit()
    return jsonify({'msg': 'Data imported successfully'}), 200

app/templates/toolkit/polling_station/index.html
{% extends 'base.html' %}

{% block title %} Polling Station {% endblock %}

{% block navbar %}
{% include 'common/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="mt-2 mb-4 d-flex justify-content-between align-items-center">
        <h1 class="display-6">Polling Station Electors' Details</h1>
        <!-- import excel btn modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#importExcelModal">
            Import Excel
        </button>
    </div>
    <!-- import form modal -->

    <div class="modal fade" id="importExcelModal" tabindex="-1" aria-labelledby="importExcelModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="importExcelModalLabel">Import Excel File</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input id="file-import-ps" type="file" name="file" id="file">
                    <button id="import-ps-excel-btn" data-api-url="{{ url_for('toolkit.ps_import') }}" type="submit" class="btn btn-primary">Import</button>
                </div>
            </div>
        </div>
    </div>

    <div class="polling-station-details">
        <table class="table table-striped table-hover table-responsive"
            data-toggle="table"
            data-toolbar=".toolbar"
            data-sortable="true"
            data-show-footer="true">
            <thead style="font-size: 12px;">
                <tr>
                    <th>Sl<br>No</th>
                    <th data-sortable="true">PART<br>NO</th>
                    <th data-sortable="true">PART<br>NAME</th>
                    <th data-sortable="true">PS<br>NO</th>
                    <th data-sortable="true">PS<br>CODE</th>
                    <th data-sortable="true">PS<br>NAME</th>
                    <th data-sortable="true">PS<br>TYPE</th>
                    <th data-sortable="true">PS<br>CATEGORY</th>
                    <th data-sortable="true">LOC<br>TYPE</th>
                    <th data-sortable="true">IS<br>Sangha</th>
                    <th data-sortable="true">ELECTORS<br>MALE</th>
                    <th data-sortable="true">ELECTORS<br>FEMALE</th>
                    <th data-sortable="true">ELECTORS<br>OTHER</th>
                    <th data-sortable="true">ELECTORS<br>TOTAL</th>
                    <th></th>
                </tr>
            </thead>
            <tbody style="font-size: 12px;">
                {% for ps in p_station %}
                    <tr>
                        <td><strong>{{ loop.index }}</strong></td>
                        <td>{{ ps.part_no }}</td>
                        <td>{{ ps.part_name }}</td>
                        <td>{{ ps.ps_no }}</td>
                        <td>{{ ps.ps_code}}</td>
                        <td>{{ ps.ps_name }}</td>
                        <td>{{ ps.ps_type }}</td>
                        <td>{{ ps.ps_category }}</td>
                        <td>{{ ps.location_type }}</td>
                        <td>{% if ps.is_sangha %}
                            <div class="modal fade" id="sanghaModal{{ ps.id }}" tabindex="-1" aria-labelledby="sanghaModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="sanghaModalLabel">{{ ps.ps_code }} - {{ ps.ps_name }}</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped table-hover table-responsive">
                                                <thead>
                                                    <tr>
                                                        <th class="text-center fs-4" colspan="4">SANGHA ELECTORS DETAILS</th>
                                                    </tr>
                                                    <tr>
                                                        <th data-sortable="true">ELECTORS<br>MALE</th>
                                                        <th data-sortable="true">ELECTORS<br>FEMALE</th>
                                                        <th data-sortable="true">ELECTORS<br>OTHER</th>
                                                        <th data-sortable="true">ELECTORS<br>TOTAL</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>{{ ps.electors_male_sangha }}</td>
                                                        <td>{{ ps.electors_female_sangha }}</td>
                                                        <td>{{ ps.electors_other_sangha }}</td>
                                                        <td>{{ ps.electors_total_sangha }}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#sanghaModal{{ ps.id }}">
                                <img src="{{ url_for('static', filename='img/icons/eye.svg') }}" 
                                        alt="view" 
                                        style="width: 17px; height: 17px;">
                            </button>


                            {% else %}
                            <button type="button" class="btn btn-danger" disabled>
                                <img src="{{ url_for('static', filename='img/icons/x-circle.svg') }}" 
                                        alt="view" 
                                        style="width: 17px; height: 17px; fill: white;">
                            </button>
                            {% endif %}
                        </td>
                        <td>{{ ps.electors_male }}</td>
                        <td>{{ ps.electors_female }}</td>
                        <td>{{ ps.electors_other }}</td>
                        <td>{{ ps.electors_total }}</td>
                        <td style="width: 10px;">
                            <button class="btn btn-outline-info btn-sm">
                                <img src="{{ url_for('static', filename='img/icons/pencil-square.svg') }}" 
                                        alt="edit" 
                                        style="width: 15px; height: 15px;">
                            </button><br>
                            <button class="btn btn-outline-danger btn-sm">
                                <img src="{{ url_for('static', filename='img/icons/trash.svg') }}" 
                                        alt="delete" 
                                        style="width: 15px; height: 15px;">
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="9">Total</th>
                    <td>{{ el_grand_total.mtotal }}</td>
                    <td>{{ el_grand_total.ftotal }}</td>
                    <td>{{ el_grand_total.ototal }}</td>
                    <td colspan="2">{{ el_grand_total.gtotal }}</td>
                </tr>
            </tfoot>
        </table>

                    
    </div>
{% endblock %}